solr:
  wikipedia-collection-name: wikipedia
  index-complete-page: false
  zookeeper-urls:
    - "solr-zoo1:12181"
    - "solr-zoo2:22181"
    - "solr-zoo3:32181"
  solr-urls:
    - "http://solr1:18983/solr"
    - "http://solr2:28983/solr"
    - "http://solr3:38983/solr"
