server:
    port: 8183
    servlet:
        context-path: /solr-query-service

management:
    endpoints:
        web:
            exposure:
                include: "mappings"
        
solr-query-service:
    query:
        params:
            query-param: "query"
            page-number-param: "pageNumber"
            items-per-page-param: "itemsPerPage"

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swaggerui.html
        operationsSorter: method

retry-config:
    initial-interval-ms: 3000
    max-interval-ms: 100000
    multiplier: 2.0
    maxAttempts: 10
    sleep-time-ms: 2000
