retry-config:
  initial-interval-ms: 3000
  max-interval-ms: 100000
  multiplier: 2.0
  maxAttempts: 10
  sleep-time-ms: 2000
wikipedia-config:
  wikipediadateformat: yyyy/MM/dd
  wikipedia-featured-feed-url: https://en.wikipedia.org/api/rest_v1/feed/featured
  index-complete-page: false
  wikipedia-page-html-api:
    base-url:  https://en.wikipedia.org/api/rest_v1/page/html
    url-params:
      - name: redirect
        value: false
  
management:
  server:
    port: 8181
  endpoints:
    enable-by-default: true
    web:
      exposure:
        include: "*"
#        exclude: "env,beans"
#      base-path: /manage
  endpoint:
    shutdown:
      enabled: true
#    info:
#      enabled: true
  
