retry-config:
  initial-interval-ms: 3000
  max-interval-ms: 100000
  multiplier: 2.0
  maxAttempts: 10
  sleep-time-ms: 2000

wikipedia-config:
  wikipediadateformat: yyyy/MM/dd
  wikipedia-featured-feed-url: https://en.wikipedia.org/api/rest_v1/feed/featured
  wikipedia-page-html-api:
    base-url:  https://en.wikipedia.org/api/rest_v1/page/html
    url-params:
      - name: redirect
        value: false
  
kafka-config.wikipedia:
  bootstrap-servers: kafka1:29092, kafka2:29093, kafka3:29094
  schema-registry-url-key: schema.registry.url
  schema-registry-url:  http://kafka-schema-registry:8081
  topic-name: wikipedia.pages
  topic-names-to-create:
    - wikipedia.pages
  number-of-partitions: 3
  replication-factor: 3
  
kafka-producer-config.wikipedia:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5
  start-date: 2019-06-22

management:
  server:
    port: 8181
  endpoints:
    enable-by-default: true
    web:
      exposure:
        include: "*"
#        exclude: "env,beans"
#      base-path: /manage
  endpoint:
    shutdown:
      enabled: true
#    info:
#      enabled: true
  