server:
  port: 8183


kafka-config.wikipedia:
  bootstrap-servers: kafka1:9092, kafka2:9093, kafka3:9094
  schema-registry-url-key: schema.registry.url
  schema-registry-url:  http://localhost:8081
  topic-name: wikipedia.pages
  topic-names-to-create:
    - wikipedia.pages
  number-of-partitions: 3
  replication-factor: 3
