server:
    port: 8184
    servlet:
        context-path: /solr-web-client
spring:
    cloud:
        loadbalancer:
            retry:
                avoidPreviousInstance: false
                
    thymeleaf:
        cache: false
    security:
        user:
            name: wams-user
            password: admin
            roles: USER

solr-query-web-client-service:
    webclient:
        connect-timeout-ms: 10000
        read-timeout-ms: 10000
        write-timeout-ms: 10000
        max-in-memory-size: 104857600 #100MB
        content-type: 'application/json'
        accept-type: 'application/json'
        solr-query-service-base-url: 'http://solr-query-service/solr-query-service/docs'
        service-id: solr-query-service
        instances:
            -
                id: elastic-query-service-1
                host: solr-query-service
                port: 8183
            -
                id: elastic-query-service-2
                host: solr-query-service
                port: 8185
            -
                id: elastic-query-service-3
                host: solr-query-service
                port: 8186

solr-query-service:
    query:
        params:
            query-param: "query"
            page-number-param: "pageNumber"
            items-per-page-param: "itemsPerPage"
        

    
