server:
  port: 8183


kafka-config.wikipedia:
  bootstrap-servers: kafka1:19092, kafka2:19093, kafka3:19094
  schema-registry-url-key: schema.registry.url
  schema-registry-url:  http://kafka-schema-registry:8081
  topic-name: wikipedia.pages
  topic-names-to-create:
    - wikipedia.pages
  number-of-partitions: 3
  replication-factor: 3
