kafka-consumer-solr-config:
  key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  consumer-group-id: wikipediaPagesToSolrTopicListenerTest002
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
# @Listener will not automatically. We will start it programatically
  auto-startup: false
  concurrency: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 15000
  internal-queue-max-size: 1000

retry-config:
  initial-interval-ms: 3000
  max-interval-ms: 100000
  multiplier: 2.0
  maxAttempts: 10
  sleep-time-ms: 2000
